project_id = "nhxrajtfxavkkzqyfrok"

[functions.chat-assistant]
verify_jwt = false

[functions.prompt-tester]
verify_jwt = false

[functions.set-user-environment]
verify_jwt = false

[functions.tutor-chat]
verify_jwt = false

[functions.learning-assistant]
verify_jwt = false